export enum AuthCodes {
    PROFILE_INCOMPLETE = "PROFILE_INCOMPLETE",
    NOT_VERIFIED = "NOT_VERIFIED",
}

export enum ErrorCodes {
    NOT_FOUND = "NOT_FOUND",
    UNAUTHORIZED = "UNAUTHORIZED",
    FORBIDDEN = "FORBIDDEN",
    BAD_REQUEST = "BAD_REQUEST",
    INTERNAL_SERVER_ERROR = "INTERNAL_SERVER_ERROR",
}


